version: "3.7"

services:
  tixati:
    image: kyzimaspb/tixati
    restart: unless-stopped
      #environment:
      #TZ: "Europe/Moscow"
    network_mode: "host"
    volumes:
      - $HOME/.tixati:/home/tixati/.tixati
